# Generated by Django 4.2 on 2024-04-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('headline', models.CharField(max_length=100, verbose_name='Head Line')),
                ('summary', models.TextField(blank=True, verbose_name="Article's Summary")),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=50, verbose_name="Category's Name")),
                ('description', models.TextField(blank=True, verbose_name="Category's Description")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('pub_name', models.CharField(max_length=50, verbose_name="Publication's Name")),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ('pub_name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('user_name',),
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='Is Allowed')),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article_app.article', verbose_name="Article's Comment")),
                ('user_name_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article_app.user', verbose_name="User Name's Comment")),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article', to='article_app.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ManyToManyField(related_name='article', to='article_app.publication', verbose_name='Publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ManyToManyField(related_name='article', to='article_app.writer', verbose_name='Writer'),
        ),
    ]
